### ISSUE TITLE
How Can I code Triple SMA

### ISSUE THREAD

**Issue by samodins** [binary-ex-machina/binaryblocks#1]
Hello,

I already have a way around adding blocks to make double SMA work well. But I want to add another SMA to it; when I added it [just like i did the double SMA] the bot does not pick up trades when the three lines cross.

I know there must be some way around it.

Can you help me please.
I can upload the xml file if need be.

Sammy

**Comment by binary-ex-machina** [comment]
@samodins, what do you mean by double SMA? using two moving averages, each one with a specific period? Do you want to get the cross of those MAs?
