### ISSUE TITLE
LOVING YOUR WORK! BUT HELP!  How do i code my bot on your platform?

### ISSUE THREAD

**Issue by HappyBotTrader** [binary-ex-machina/binaryblocks#12]
i have been searching endlessly to find a way to get my bot to stop trading after 3 consecutive losses, every time I've tried to add pause functions to block 4 or even within "this block runs every tick" it still doesn't respect the codes inserted, I am at a total lost. Could you please code add these features?

Conditions are :

IF 4 CONSECUTIVE LOSSES, THEN PAUSE FOR 5 MINS , THEN START TRADE AGAIN.

IF LOSS IS MORE THAN MAX ACCEPTABLE LOSS , THEN PAUSE TRADING FOR 40 MINS, THEN START TRADE AGAIN.

I've attached a screenshot of my current blocks and xml file, please let me know
![Git Hub Bot Help](https://user-images.githubusercontent.com/127138528/223281811-878607ae-2fd5-410a-95f1-068e04ee2927.PNG)

Bot XML Google Drive- https://drive.google.com/file/d/1mXdtvpsAgy0NPzzYhy91i8WGNWZsZkyW/view?usp=share_link

 Thanks in advance

**Comment by binary-ex-machina** [comment]
I won't be able to edit your bot, but I can show you how to implement this idea. Please take a look at the image below.

Change the parameters as you need. Download the file here 
[even odd with timers.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/10904052/even.odd.with.timers.json.zip) and use it here https://binaryblocks.pro/

![image](https://user-images.githubusercontent.com/34610787/223286791-07638a72-3041-4cb7-9e18-0e5a05efd50e.png)

**Comment by HappyBotTrader** [comment]
> I won't be able to edit your bot, but I can show you how to implement this idea. Please take a look at the image below.
> 
> Change the parameters as you need. Download the file here [even odd with timers.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/10904052/even.odd.with.timers.json.zip) and use it here https://binaryblocks.pro/
> 
> ![image](https://user-images.githubusercontent.com/34610787/223286791-07638a72-3041-4cb7-9e18-0e5a05efd50e.png)

THANK YOU, you are a real RoboCop Programmer ! I will test this and let you know the results.

**Comment by binary-ex-machina** [comment]
@kidamuye, I need to know more about the strategy the bot uses. Create a new issue and post in there and I may help you

**Comment by kidamuye** [comment]
I have replied but to add upon it the bot am talking about looks like this


https://youtu.be/XIlI7m8WdPU
