### ISSUE TITLE
Perda virtual - Entrar após padrão

### ISSUE THREAD

**Issue by ghost** [binary-ex-machina/binaryblocks#15]
É possível usar a perda virtual neste padrão? Uso o BinaryBlocks com perdas virtuais, mas não consegui configurar (ou não tem como) esse padrão de operação:

![img1](https://user-images.githubusercontent.com/131908434/234668812-57a81f97-33e0-415b-9b13-f3f1834b2e9c.PNG)

![img2](https://user-images.githubusercontent.com/131908434/234669959-29558d75-74c7-4d98-af5a-377e0f6c8ec6.PNG)

Em resumo, ele realiza várias compras na conta virtual até perder uma única vez, depois de perder, ele compra novamente esperando que ganhe o contrato e se ganhar, aí sim ele entra na conta real. Na conta real, se ele perder, ele compra novamente na até achar a vitória.

**Comment by binary-ex-machina** [comment]
@rej61w a seguir os blocos que você pode usar para criar a sua estratégia. A maior parte da lógica vai ficar no bloco de resultado do contrato. Na seta vermelha você coloca o token da conta que vai receber as trades virtuais

Faça o download to bot aqui [custom virtual.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/11346263/custom.virtual.json.zip)

Use ele em https://binaryblocks.pro/


![image](https://user-images.githubusercontent.com/34610787/234936553-2afb8e75-bb73-44ad-b681-6fe3a5ea6247.png)


Aqui um exemplo dos resultados com esta estratégia

![image](https://user-images.githubusercontent.com/34610787/234935701-5cc7dd30-edd1-4d1a-91ec-0d6dce83d56d.png)
