### ISSUE TITLE
even odd with timers we worked

### ISSUE THREAD

**Issue by Ukamixx** [binary-ex-machina/binaryblocks#19]
i am trying to add the condition that it does the opposite in the "Before Purchase Block" or in general after detecting 2 consecutive losing streaks of 4 losses. Can you
[even.odd.with.timers.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/11645898/even.odd.with.timers.json.zip)
 add this condition instead of the wait time? Thanks

**Comment by binary-ex-machina** [comment]
@Ukamixx I didn't understand. You want the bot to wait for 2 losing streaks of 4 losses, then do what?

**Comment by Ukamixx** [comment]
Hey Binary-Ex-Machina,


Thanks for replying, i explained it better here on github. Also i would
want take profit to be a percentage of 5 or 10% of account balance as the
only options


https://github.com/binary-ex-machina/binaryblocks/issues/17

Thanks for your time bro.

**Comment by Ukamixx** [comment]
Robo Cop Developer ! Thanks for the good bot. I am currently testing but i
do not see supertrend indicator block to fine tune setting ..
