### ISSUE TITLE
how make stochastic and rsi bot using your binary blocks

### ISSUE THREAD

**Issue by shakboss** [binary-ex-machina/binaryblocks#2]
Hey i would like to create stochastic cross up and cross down bot with rsi saying over bought or over sold to work as one to place trade 
I dont know how to setup purchase faze 
![Capture](https://user-images.githubusercontent.com/103835298/193603040-a9d549a5-d3b3-4009-947c-00abba5c8127.PNG)

**Comment by binary-ex-machina** [comment]
@shakboss, you can do like this
![image](https://user-images.githubusercontent.com/34610787/193620928-b68eb25e-01c4-40a3-8ced-2859124c7dec.png)

[stoch and rsi.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/9698931/stoch.and.rsi.json.zip)

**Comment by shakboss** [comment]
thanks alot man
