### ISSUE TITLE
Teste de Kendall

### ISSUE THREAD

**Issue by guilhermej2h** [binary-ex-machina/binaryblocks#21]
Quero implantar um Teste de Kendall em uma `lista` de 10 RSI no robô em [anexo.](https://drive.google.com/file/d/1ULkMgJqLZPxASwGzrzvlEifL4Q5gDtbJ/view?usp=sharing)

**Comment by binary-ex-machina** [comment]
Preciso de uma ideia melhor do que é este teste de kendall

**Comment by guilhermej2h** [comment]
O teste de Kendall, também conhecido como coeficiente de concordância de Kendall ou Tau de Kendall, é uma medida estatística não paramétrica utilizada para avaliar a concordância ou a associação entre duas variáveis ordinais. Ele foi desenvolvido por Maurice Kendall em 1938.

O teste de Kendall compara as classificações ou ordens de duas variáveis e calcula o coeficiente de concordância de Kendall (Tau de Kendall). O valor de Tau de Kendall varia de -1 a 1. Os seguintes intervalos são usados para interpretar o valor de Tau:

-1: Indica uma concordância total inversa. Ou seja, quanto maior o valor de uma variável, menor o valor da outra variável.

0: Indica nenhuma concordância ou associação entre as variáveis.

1: Indica uma concordância total. Ou seja, quanto maior o valor de uma variável, maior o valor da outra variável.

Para realizar o teste de Kendall, primeiro, as classificações ou ordens das duas variáveis são obtidas. Em seguida, os pares de observações são comparados para determinar se estão em concordância ou discordância. Por fim, o coeficiente de concordância de Kendall é calculado com base no número de pares concordantes e discordantes.

Existem várias versões do teste de Kendall, como Tau-b e Tau-c, que levam em consideração os empates nas classificações. Essas versões ajustam o coeficiente de concordância de Kendall para levar em conta a presença de empates nas classificações das variáveis.

O teste de Kendall é amplamente utilizado em diversas áreas, como ciências sociais, estatística, psicologia, economia e biologia, quando as variáveis de interesse são ordinais e não seguem uma distribuição normal. Ele fornece uma medida robusta da associação entre as variáveis ordinais, independentemente da forma da distribuição ou da presença de outliers.
O teste de Kendall também pode ser aplicado na verificação de sequências monotônicas, ou seja, sequências de números que seguem uma ordem crescente ou decrescente.

Suponha que você tenha uma sequência de números e deseja determinar se ela é monotônica crescente ou monotônica decrescente. O teste de Kendall pode ajudar nessa verificação.

Vamos considerar a seguinte sequência de números:

2, 5, 3, 1, 4

Para aplicar o teste de Kendall, você precisa comparar cada par de elementos e verificar se eles estão em ordem crescente ou decrescente.

Comparando o primeiro par (2 e 5), temos que 2 é menor que 5. Portanto, há concordância.

Continuando com as comparações, encontramos os seguintes resultados:

Pares concordantes: (2, 5), (2, 3), (2, 4), (5, 3), (5, 4), (3, 4)
Pares discordantes: (5, 1), (3, 1), (1, 4)
Agora, calculamos o coeficiente de concordância de Kendall (Tau de Kendall) usando a fórmula:

Tau = (Concordantes - Discordantes) / (Concordantes + Discordantes)

No nosso exemplo, temos:

Concordantes = 6
Discordantes = 3

Tau = (6 - 3) / (6 + 3) = 3 / 9 = 1/3

Portanto, o coeficiente de concordância de Kendall (Tau de Kendall) para essa sequência é 1/3. Isso indica uma concordância leve, mas não monotônica, já que a sequência não é estritamente crescente ou estritamente decrescente.

Ao aplicar o teste de Kendall em uma sequência monotônica, se todos os pares comparados apresentarem concordância, o coeficiente de concordância de Kendall será igual a 1. Caso contrário, se houver pelo menos um par discordante, o coeficiente será menor que 1.

Exemplo
Função verificaMonotonicidade(sequencia):
    concordantes = 0
    discordantes = 0
    
    Para i de 1 até o tamanho da sequencia - 1:
        Para j de i + 1 até o tamanho da sequencia:
            Se sequencia[i] < sequencia[j]:
                concordantes += 1
            Senão:
                discordantes += 1
    
    tau = (concordantes - discordantes) / (concordantes + discordantes)
    
    Se tau = 1:
        Retorne "A sequência é monotônica crescente."
    Senão, se tau = -1:
        Retorne "A sequência é monotônica decrescente."
    Senão:
        Retorne "A sequência não é monotônica."

**Comment by guilhermej2h** [comment]
No caso quero que o robô adquira quando a sequência RSI for provada crescente.

**Comment by binary-ex-machina** [comment]
Fiz algumas alterações. Sendo que o bot faz diversos cálculos, eu removi eles do bloco que funciona em cada tick e coloquei eles em uma função que só é chamada quando não tiver nenuma trade em andamento. Isso ajuda a diminuir o processamento da página quando você apertar o play

abaixo tem a parte onde você compara o valor do TAU. Coloquei igual a 1 já que você ta usando barreira positiva. Se for negativa, acredito que o valor desejado seja -1

![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/6d8f5c7d-4210-4eb8-8f55-35d078efdb84)

Download [tau.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/11940387/tau.json.zip) e use em [https://binaryblocks.pro/](url)

**Comment by guilhermej2h** [comment]
Ficou ótimo.
Fiz um ajuste com a inclusão do RSI Stocastico, porém não consegui implantá-lo na sua Função.
Vou verificar se crio um contador de TAU, para que a entrada ocorra após o segundo ou terceiro = a 1

**Comment by guilhermej2h** [comment]
TAU [2.0](https://drive.google.com/file/d/1UBeKk24tVBTEODZ-DMv_AlpOyB2UakC8/view?usp=sharing)

**Comment by guilhermej2h** [comment]
Porém gostaria que ele contasse quando o TAU se repetisse de forma crescente em sequencia.

**Comment by guilhermej2h** [comment]
Versão com ajustes e Contador de TAU. Bom desempenho mais falta enxugar o código TAU 2.0 [](https://drive.google.com/file/d/1SgY1rardnJG8Kw8_qebfFVRu5l1k3RdE/view?usp=sharing)

**Comment by guilhermej2h** [comment]
Versão com ajustes e Contador de TAU. Bom desempenho mais falta enxugar o código TAU 2.0[https://drive.google.com/file/d/1SgY1rardnJG8Kw8_qebfFVRu5l1k3RdE/view?usp=sharing](url)

**Comment by guilhermej2h** [comment]
Versão com ajustes e Contador de TAU. Bom desempenho mais falta enxugar o código [TAU 2.0](https://drive.google.com/file/d/1SgY1rardnJG8Kw8_qebfFVRu5l1k3RdE/view?usp=sharing)

**Comment by guilhermej2h** [comment]
Uma sequência é considerada monotônica se todos os seus termos seguem uma determinada ordem crescente ou decrescente. Para verificar se uma sequência é monotônica, siga estes passos:

Identifique se a sequência é crescente ou decrescente. Isso significa verificar se cada termo subsequente é maior ou menor que o termo anterior. Se todos os termos são estritamente maiores (ou estritamente menores) do que os termos anteriores, a sequência é monotonicamente crescente (ou decrescente). Caso contrário, prossiga para o próximo passo.

Verifique se a sequência é monotônica não estritamente crescente ou decrescente. Isso significa que os termos subsequentes podem ser iguais aos termos anteriores, mas não podem ser menores (ou maiores) do que eles. Se todos os termos são maiores ou iguais (ou menores ou iguais) aos termos anteriores, a sequência é monotonicamente não estritamente crescente (ou decrescente). Caso contrário, a sequência não é monotônica.

Aqui estão alguns exemplos para ilustrar esses conceitos:

Exemplo 1:
Sequência: 1, 3, 5, 7, 9
A sequência é monotonicamente crescente, pois cada termo subsequente é estritamente maior que o termo anterior.

Exemplo 2:
Sequência: 5, 4, 3, 2, 1
A sequência é monotonicamente decrescente, pois cada termo subsequente é estritamente menor que o termo anterior.

Exemplo 3:
Sequência: 2, 4, 4, 6, 8
A sequência é monotonicamente não estritamente crescente, pois cada termo subsequente é maior ou igual ao termo anterior.

Exemplo 4:
Sequência: 10, 8, 8, 5, 2
A sequência não é monotônica, pois os termos subsequentes não seguem uma ordem crescente ou decrescente.

Lembrando que essas regras valem tanto para sequências numéricas quanto para sequências de outros elementos ordenáveis.

Gostaria de um  algoritimo similar
Função verificarMonotonicidade(sequência):
    se o comprimento da sequência for menor ou igual a 1:
        retorne verdadeiro  // sequência vazia ou com apenas um elemento é considerada monotônica

    definir uma variável booleana crescente como verdadeiro
    definir uma variável booleana decrescente como verdadeiro

    para i de 1 até o comprimento da sequência - 1:
        se sequência[i] > sequência[i-1]:
            decrescente = falso
        senão, se sequência[i] < sequência[i-1]:
            crescente = falso

    se crescente for verdadeiro ou decrescente for verdadeiro:
        retorne verdadeiro  // a sequência é monotônica
    senão:
        retorne falso  // a sequência não é monotônica

**Comment by guilhermej2h** [comment]
Poderia ajustar pra mim por favor?

**Comment by guilhermej2h** [comment]
Baixa o Bot do comentário anterior hoje, que tem o Link com as configurações mais atuais.
