### ISSUE TITLE
Robô Cyclope

### ISSUE THREAD

**Issue by guilhermej2h** [binary-ex-machina/binaryblocks#24]
Tenho este Robô Even ODD com múltiplas estratégias que se mantem adquirindo enquanto está em WIN.
Verifica-se que Robôs EVEN ODD permitem longas sequências de WIN e de LOSS, porém não sei como prever razoavelmente.
Gostaria que verificasse a possibilidade de após certo ganho de proteção do capital, o robô contasse a cada 4 WIN e fizesse entrada em SOROS afim de alcançar a META mais rapidamente.
Ex.:
Entrada> 0,35
WIN>  0,31
WIN>  0,31
WIN>  0,31
WIN>  0,31
Total de WIN 1,24
Entrada Após a Contagem de 4 Wins = 1,24
Entradas posterior =1,24 + Lucro enquanto for WIN
Caso for Loss , Entrada = 0,35 em Martingale = 0,70.

Segue [Bot](https://drive.google.com/file/d/1uanH7rHso0_WYTyW7HVmmhnV2janRKoz/view?usp=sharing)

**Comment by binary-ex-machina** [comment]
você pode fazer um contador de vitorias e aplicar o soros quando o contador chegar no valor que você quer

![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/a3bc4df3-3722-4455-af95-1aff0895ac49)
