### ISSUE TITLE
Robô DifereBZ

### ISSUE THREAD

**Issue by guilhermej2h** [binary-ex-machina/binaryblocks#25]
Olá tudo bem?
Estou desenvolvendo este Bot [Difere](https://drive.google.com/file/d/1v5pMny_PHTKnTvYudhYfWU8sayW3hlJK/view?usp=sharing) que tem a seguinte proposta:
Quando a porcentagem de zero estiver baixando a porcentagem(decrescente) e algum dígito de 1 a 9 for superior a uma porcentagem > que 30% ou 32%, faz a entrada.
Para tanto tentei criar uma lista de porcentagens dos dígitos de 1 a 9 e uma Variável chamada Maior Porcentagem, para que todas as porcentagens sejam comparadas com a Variável. 
Exemplo:
Inicialize uma variável chamada maior_porcentagem como zero.
Percorra a lista de porcentagens.
Para cada porcentagem na lista, verifique se ela é maior do que a maior_porcentagem atual. Se sim, atualize o valor de maior_porcentagem para a nova porcentagem.
Após percorrer toda a lista, a variável maior_porcentagem conterá o valor da maior porcentagem

def encontrar_maior_porcentagem(lista_porcentagens):
    maior_porcentagem = 0
    
    for porcentagem in lista_porcentagens:
        if porcentagem > maior_porcentagem:
            maior_porcentagem = porcentagem
    
    return maior_porcentagem

A parte da monotocidade de zero está Ok,.
Porém encontrar a maior porcentagem que não seja o zero, tentei fazer de algumas formas, porém sem sucesso.
Segue Bot em [Anexo](https://drive.google.com/file/d/1v5pMny_PHTKnTvYudhYfWU8sayW3hlJK/view?usp=sharing)

Obs: Imprimi alguns dígitos da função que informa a porcentagem do dígito nos últimos x dígitos, porém verifiquei que não estão muito consistentes, assim como não consegui imprimir quando passado para lista.
Quando vou imprimir por exemplo o 0 e 1 ele imprime a porcentagem somente de um dos dígitos.
Grato!

**Comment by guilhermej2h** [comment]
> Olá tudo bem? Estou desenvolvendo este Bot [Difere](https://drive.google.com/file/d/1v5pMny_PHTKnTvYudhYfWU8sayW3hlJK/view?usp=sharing) que tem a seguinte proposta: Quando a porcentagem de zero estiver baixando a porcentagem(decrescente) e algum dígito de 1 a 9 for superior a uma porcentagem > que 30% ou 32%, faz a entrada. Para tanto tentei criar uma lista de porcentagens dos dígitos de 1 a 9 e uma Variável chamada Maior Porcentagem, para todas as porcentagens sejam comparadas a variável. Exemplo: Inicialize uma variável chamada maior_porcentagem como zero. Percorra a lista de porcentagens. Para cada porcentagem na lista, verifique se ela é maior do que a maior_porcentagem atual. Se sim, atualize o valor de maior_porcentagem para a nova porcentagem. Após percorrer toda a lista, a variável maior_porcentagem conterá o valor da maior porcentagem
> 
> def encontrar_maior_porcentagem(lista_porcentagens): maior_porcentagem = 0
> 
> ```
> for porcentagem in lista_porcentagens:
>     if porcentagem > maior_porcentagem:
>         maior_porcentagem = porcentagem
> 
> return maior_porcentagem
> ```
> 
> A parte da monotocidade de zero está Ok,. Porém encontrar a maior porcentagem que não seja o zero, tentei fazer de algumas formas, porém sem sucesso. Segue Bot em [Anexo](https://drive.google.com/file/d/1v5pMny_PHTKnTvYudhYfWU8sayW3hlJK/view?usp=sharing) Grato!

**Comment by binary-ex-machina** [comment]
você pode usar os blocos do menu de dígitos para pegar os dígitos que mais aparecem e que menos aparecem, assim como a porcentagem de algum dígito específico no número de ticks que você deseja

![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/d206969a-0b2f-4d97-9d6b-bb04d59f8f7b)

**Comment by guilhermej2h** [comment]
Quando eu pego estes da porcentagem para usar de forma simultanea o Bot não lê individual.
Ao imprimir por exemplo 0 e 1 ele imprime somente um deles.

**Comment by binary-ex-machina** [comment]
Vc pode fazer assim para comparar mais de um dígito

![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/46f5abdb-d5e5-4277-aabd-e5a048453d9f)

**Comment by guilhermej2h** [comment]
Mais já testei desta forma.
Quando um deles bate a barreira da comparação o Bot executa a ordem.
Por exemplo se eu quiser que um Bot faça entradas quando 0 estiver abaixo de 4% e os demais acima de 4%, o Bot não executa a ordem, ou executa se qualquer um deles atingir acima de 4%.

**Comment by binary-ex-machina** [comment]
Aqui está funcionando normal, testa este arquivo

[digits.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/12065381/digits.json.zip)

**Comment by guilhermej2h** [comment]
Agora faz o seguinte teste:
Executa o Arquivo e Coloca a tela em lado a lado com a estatistica do https://smarttrader.deriv.com/

![Testedeporcentagens](https://github.com/binary-ex-machina/binaryblocks/assets/133600710/b785b0e1-9cad-49e4-a9c6-143ed7b0dd22)

Observe que as porcentagens não estão em sincronia.
