### ISSUE TITLE
Lista de últimos dígitos de tique taques

### ISSUE THREAD

**Issue by guilhermej2h** [binary-ex-machina/binaryblocks#26]
Tentei criar uma função de porcentagem, porém quando crio uma sublista de 25 dígitos, o último dígito não bate com o dígito do último tique taque.

Quando crio em https://bot.deriv.com/, ele bate.

![Calculo de porcentagem](https://github.com/binary-ex-machina/binaryblocks/assets/133600710/b8556b06-9795-4d2f-b716-627ecfae1386)

**Comment by binary-ex-machina** [comment]
Fiz um teste aqui e funcionou normal

![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/fb720128-5789-468d-bf70-1fb2ade7aa07)

**Comment by guilhermej2h** [comment]
NÃO. O que eu quero no caso é o último dígito da parte fracionária. O último dígito do Tique taque.

**Comment by guilhermej2h** [comment]
Resolvi aqui
Obrigado!
