### ISSUE TITLE
Bot não Salva

### ISSUE THREAD

**Issue by guilhermej2h** [binary-ex-machina/binaryblocks#28]
Hoje tentei salvar um Bot, porém não Consigo abrir o arquivo salvo. Aparece mensagem que os Blocos não  carregam.

**Comment by binary-ex-machina** [comment]
De onde você baixou o bot? consegue mandar ele aqui para teste?

**Comment by guilhermej2h** [comment]
Consertou aqui. Minha máquina estava com Vírus.

**Comment by guilhermej2h** [comment]
Obrigado

**Comment by guilhermej2h** [comment]
Acontece quando uso indicadores e cruzamento de indicadores. 
Acredito que tenha que declarar variável para usar no cruzamento, para que salve corretamente.

**Comment by binary-ex-machina** [comment]
Sempre salve o retorno dos indicadores em uma variável. Assim quando fizer o carregamento ele não de erros

**Comment by guilhermej2h** [comment]
OK
