### ISSUE TITLE
BOT CRUZAPARABÓLICA

### ISSUE THREAD

**Issue by guilhermej2h** [binary-ex-machina/binaryblocks#30]
Olá, tudo bem?
Criei este Bot, na Plataforma binaryblocks.pro, e gostaria que o Bot desse entrada no Cruzamento X.

Eles está entrando alguns tick após o cruzamento. Gostaria de Saber se tem como ele fazer a entrada  no cruzamento X subindo ou se tem algum indicador que poderia usar para melhorar a assertividade.
Tentei calcular a Diferença dos SMA para dar entrada quando fosse 1, mais não foi aceito o critério.
Por último incluí o calculo da diferença do resto da divisão dos SMA.

Segue o Bot.
[CRUZAPARABOLICA](https://drive.google.com/file/d/1oYXDG5HwQhK58CJ8qA-hYS6JB2kjww48/view?usp=sharing)

**Comment by binary-ex-machina** [comment]
olá, dei uma olhada no bot e está tudo certo com o que vc quer fazer. Qual seria o problema dele?

**Comment by guilhermej2h** [comment]
Gostaria que a entrada iniciasse no início do  tick ou da vela.
