### ISSUE TITLE
Desenvolvimento Bot CRUZBOLL

### ISSUE THREAD

**Issue by guilhermej2h** [binary-ex-machina/binaryblocks#31]
Tenho este Bot que entra Toca quando a Bolling Band Superior cruza a média móvel de 10 e quanto a Média Móvel 1 é maior que a Média Móvel 10, e quando há 3 ticks subindo simultaneamente.
Gostaria de melhoria no sentido de desempenho.
Obs.: Verificar a possibilidade de desenvolver uma versão com Martingale.

Segue o Bot [CRUZBOLL](https://drive.google.com/file/d/1sIiT0CNjKuyTlt1f_HUJCiSeYQCOmhFm/view?usp=sharing)

**Comment by binary-ex-machina** [comment]
Melhorar ele fica muito subjetivo. No lugar de SMA com período 1 é a mesma coisa que vc comparar o tick atual com o valor do SMA com 50 períodos. Talvez mudar a duração para 15 ou 30 segundos. Para adicionar o martingale, confere na parte de Money Management, cada bloco tem no nome onde ele deve ir.

Aqui o arquivo com martingale [cruzbool com martingale.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/12316919/cruzbool.com.martingale.json.zip)
