### ISSUE TITLE
BOT KCTOCA

### ISSUE THREAD

**Issue by guilhermej2h** [binary-ex-machina/binaryblocks#32]
Bom dia!

Amigo eu desenvolvi este Bot com estratégia de Canal de Kettener, porém ele rodou uma vez e agora não vejo mais ele fazer entradas.  
Poderia analisar se está tudo bem com o código.

Segue arquivo em [Anexo](https://drive.google.com/file/d/1C0Qt1ET4gv6Ktbsbk4nbTktFG6g3yZwz/view?usp=sharing)

**Comment by binary-ex-machina** [comment]
Pelo que olhei aqui, tem algumas coisas fora do lugar. Na questão da estratégia, você pode colocar uma notificação para ver quais valores estõa sendo usados. É complicado ver esta estratégia no gráfico, pois você usa ticks em um dos indicadores, mas ele deveria fazer várias trades, não apenas uma e parar. Dependendo da meta que você colocar, ele vai fazer mais de uma trade.

A aposta Inicial precisa vir antes do bloco do martingale, pois você define ele antes

Original
![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/ec5fccf0-9ca7-4ff0-8c63-c89bc4e3696d)

Correto
![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/bb76da9e-b2d4-4063-b194-6dee87b67201)

Aqui nest aparte, se você quer que o bot pare quando atingir o alvo, você pode diminuir a repetição de blocos

Original
![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/3f38ff79-2758-44e1-8774-57d2aeea90ba)

Correto
![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/8ca77d0f-7c4e-4c5a-a800-f0f5536baab4)

Nesta parte, você pode colocar apenas uma das validações dos segundos. Além disso, coloca todas os cálculos para acontecer neste primeiro segundo da vela

Original
![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/7bdfdf73-38f5-4f09-9c3c-e72c159c1be2)

Alterado
![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/faa8ae9c-6038-4f63-a6d9-b1aa0ef6efd3)

Agora analisando com os blocos no lugar certo, usar o martingale é ruim neste caso, já que você muda o stake inicial sem usar o martingale. Acredito que o melhor é fazer como na imagem abaixo

![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/60291465-ae82-4880-85b9-103efdbf7827)


[keltener + sma.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/12350696/keltener.%2B.sma.json.zip)

**Comment by guilhermej2h** [comment]
Ótimo!
Muito Obrigado!
