### ISSUE TITLE
Indiador Aroon

### ISSUE THREAD

**Issue by guilhermej2h** [binary-ex-machina/binaryblocks#33]
Gostaria que enviasse um Bot com indicador Aroon, pois quando utilizo aqui o mesmo não está em sincronia com https://app.deriv.com/.

**Comment by binary-ex-machina** [comment]
Os cálculos deste indicador no site da Deriv são feitos de forma diferente do convencional. Os indicadores do blocks são feitos com base no tradingview da Deriv https://tradingview.deriv.com/deriv
