### ISSUE TITLE
Bot PROBTAU1.0

### ISSUE THREAD

**Issue by guilhermej2h** [binary-ex-machina/binaryblocks#35]
Olá tudo bem?
Espero que sim.
Estou desenvolvendo um Bot do tipo Toca na Volatividade 25, com análise decrescente do SMA em que as entradas são feitas quando a tendência numérica por meio de cálculo matemático indica que vai ocorrer uma ruptura de queda.
Porém gostaria de implementar mais um teste conforme abaixo:
Quando você tem uma sequência que não é crescente nem decrescente, mas deseja analisar a tendência geral de crescimento ou decrescimento, pode ser útil calcular a média das inclinações entre os pares consecutivos de elementos na sequência. Isso pode lhe dar uma ideia da tendência geral da sequência, mesmo que haja flutuações individuais.

Vou explicar o processo usando um exemplo:

Suponha que você tenha a seguinte sequência:

Sequência: 5, 3, 7, 6, 8, 10, 9, 12, 11, 14

Para calcular a tendência geral, você pode calcular as inclinações entre cada elemento consecutivo. Se a maioria das inclinações para positiva, isso indicará uma tendência crescente. Se a maioria das inclinações para negativa, indicará uma tendência decrescente. Vamos fazer esses cálculos:

![tend](https://github.com/binary-ex-machina/binaryblocks/assets/133600710/ad3c5dd5-c22b-4967-ac29-39218db6be23)

Agora, some todas as inclinações e divida pelo número total de pares para obter uma média:

![media](https://github.com/binary-ex-machina/binaryblocks/assets/133600710/9bf89f57-eebc-47de-9e00-7f788c6ec135)

Como a média das inclinações é positiva (1), isso sugere uma tendência geral de crescimento na sequência, apesar das flutuações individuais. Lembre-se de que essa é uma abordagem simples e que as características da sequência podem variar em diferentes contextos.

Segue o Arquivo na versão sem o [cálculo](https://drive.google.com/file/d/1mLdciSjVU5nRcXrkrCQvVAs0yiYkmiMt/view?usp=sharing)

E o arquivo com o [cálculo](https://drive.google.com/file/d/1QRXR5QR24aoe3F1eQvGbwOoEYfxI9ftb/view?usp=sharing)

Favor analisar o ultimo arquivo em que criei uma lista de 5 últimos SMA afim de realizar o cálculo.
Favor verificar a possibilidade de criar o cálculo utilizando estrutura de repetição ou função afim de possibilitar aumentar o Ranger.

**Comment by binary-ex-machina** [comment]
Segue como você pode comparar os valores de uma lista. No exemplo estou usando uma média móvel de 20 períodos com uma lista de ticks. Da para fazer esta ideia com qualquer indicador ou lista, apenas compara o valor de um item com outro e coloca esse valor em uma variável. Vai alterando esta variável com os novos valores (acrescentando ou diminuindo). e depois divide pelo número de itens. - 1. 

[média.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/12440683/media.json.zip)

![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/bb96800d-20d8-4b73-8686-9076c608e300)

**Comment by guilhermej2h** [comment]
No caso então eu faria as entradas quando a média ficar decrescente? Média < 0.

**Comment by binary-ex-machina** [comment]
dai vai conforme a sua estratégia. O código que mandei há esta contando e já esta usando a sua formula. Confere os dados de alerta

**Comment by guilhermej2h** [comment]
ok
