### ISSUE TITLE
touch,no touch bot

### ISSUE THREAD

**Issue by mucugi** [binary-ex-machina/binaryblocks#36]
can you plz, create a touch bot, that uses cci indicator for direction purposes.if points down it trade put,whereelse if it points upwards it trades call

**Comment by binary-ex-machina** [comment]
@mucugi, you can do like the image below

Download: [cci touch.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/12728897/cci.touch.json.zip)


Run it here https://binaryblocks.pro/
![Screenshot 2023-09-22 at 13 23 04](https://github.com/binary-com/binary-bot/assets/34610787/89abdfb5-309c-4419-88e3-35ab2417c2ef)


![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/412cfcaa-995d-428e-aabb-fd0466055bcf)
