### ISSUE TITLE
TOUCH NOTOUCH

### ISSUE THREAD

**Issue by mucugi** [binary-ex-machina/binaryblocks#37]
help create a bot that analyses using stochastic indicator.when k>D TRADES CALL and k<d trade put.

**Comment by binary-ex-machina** [comment]
You can do like this image below

[stochastic crosser.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/12821071/stochastic.crosser.json.zip)


![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/7bc2bf11-f247-4a0e-aca8-50e0b476e82e)

**Comment by mucugi** [comment]
Thanks a lot it's perfectly
