### ISSUE TITLE
Como resolver problema com tempo de operação?

### ISSUE THREAD

**Issue by 7hermal** [binary-ex-machina/binaryblocks#40]
![image](https://github.com/binary-ex-machina/binaryblocks/assets/146600578/25a60055-2f85-4bc7-97bb-1bd01c147394)
![image](https://github.com/binary-ex-machina/binaryblocks/assets/146600578/b5fe01a9-72da-4794-a752-503fdc5199e1)
![image](https://github.com/binary-ex-machina/binaryblocks/assets/146600578/c9f8a1da-072e-4092-8538-9d6b7dff54c5)

A ideia é simples, quando o último tick for maior/menor que o valor mais alto/baixo da vela anterior, entro numa operação com o tempo restante da vela de M1. O problema é que não está respeitando, com anexado. O cruzamento ocorreu às 20:28:16, o tempo restante de vela seria 44 segundos, não 55 (60-16 = 44), como na imagem. Existe alguma formar de mitigar esse problema? Ou é um erro meu de codificação?

**Comment by binary-ex-machina** [comment]
@7hermal, a analise precisa ser feita antes da trade ser definida. A parte de Trade Options, depois de lida, não tem como ser modificada. No seu exemplo o tempo da trade é definido antes da analise, então vai sempre ter diferença. Vc pode usar o bloco de loop antes de definir a duração da trade, fazendo a analise do mercado ali e então definindo a duração com base na analise.

Download: [end of the candle.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/12820907/end.of.the.candle.json.zip)


![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/ed6d2c6d-0012-41c9-bffe-02f032572955)

**Comment by 7hermal** [comment]
Obrigado pelo ajuda, não sabia dessa parte e o erro foi meu. Deixei rodando por alguns minutos aqui ele não errou o tempo.
