### ISSUE TITLE
binary blocks

### ISSUE THREAD

**Issue by shakboss** [binary-ex-machina/binaryblocks#41]
could u help build a bot with rsi and also cci pattern ?
i want it like cci and rsi over 50 with a bullish engulfing pattern to buy and well the other way around for sell plz and thanks

**Comment by binary-ex-machina** [comment]
@shakboss Here is the strategy. Change the periods of the CCI and RSI as you need

![image](https://github.com/binary-ex-machina/binaryblocks/assets/34610787/83f75402-fd7e-4214-9aca-616e2b6fd149)


Download it here:  [RSI + CCI + Engulfing.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/13780892/RSI.%2B.CCI.%2B.Engulfing.json.zip)


Run it at https://binaryblocks.pro/

![Screenshot 2023-10-25 at 13 35 02](https://github.com/binary-com/binary-bot/assets/34610787/1f77e711-fbd0-4572-a49a-45b958b475e8)

**Comment by shakboss** [comment]
thanks so  much sir
