### ISSUE TITLE
I need to understand how to harness the power of "virtual trades"

### ISSUE THREAD

**Issue by hmebert1980** [binary-ex-machina/binaryblocks#42]
Dear Thiago,

Can you please explain to me how the "Virtual Trade Settings" block works?

![image](https://github.com/binary-ex-machina/binaryblocks/assets/44832799/6b61275c-c6f3-472d-b791-7c462d24e758)

If I need to test my strategy on my Demo account first, what is the token I should use?

Also, it would help to see a sample bot that runs virtual trades so I can use it as a reference to build my own.

**Comment by binary-ex-machina** [comment]
Hello, you should use a second account token, so the trades will be done in there

Check this tutorial on the Virtual Trades

https://www.youtube.com/watch?v=YdkA_ye3P44
