### ISSUE TITLE
bot request

### ISSUE THREAD

**Issue by c4ke254** [binary-ex-machina/binaryblocks#45]
Entry Signals:
Call Option (Buy):
The 5 EMA crosses above the 10 EMA, indicating an upward trend.
RSI is above 50 but not overbought (below 70).
Put Option (Sell):
The 5 EMA crosses below the 10 EMA, indicating a downward trend.
RSI is below 50 but not oversold (above 30).

**Comment by binary-ex-machina** [comment]
The bot is here, I used ticks as source and 5 ticks as duration

Download it here:  [EMA RSI Cross.json.zip](https://github.com/user-attachments/files/16444493/EMA.RSI.Cross.json.zip)

Run it at https://binaryblocks.pro/

![Screenshot 2023-10-25 at 13 35 02](https://github.com/binary-com/binary-bot/assets/34610787/1f77e711-fbd0-4572-a49a-45b958b475e8)

![image](https://github.com/user-attachments/assets/2537d8db-5052-41de-80b7-02a672d28289)
