### ISSUE TITLE
Under 9, switch to either Over 5 or Under 6 Strategy

### ISSUE THREAD

**Issue by FrancisMairura** [binary-ex-machina/binaryblocks#46]
Hey ! I'd kindly need assistance refining my bot with the following conditions

The bot runs under 9. 

If it loses the 1st time, checks the last digit and:
_1. If the last digit is 2,3,4 or 5, it switches to over 5
2. If the last digit is 0,1,7,8 or 9, the bot switches to under 6_

The martingale is 2.1

If it loses the 2nd time, similar conditions as above. Once it gets to the 4th loss it goes back to initial stake and goes back to under 9. It keeps on bringing an error where it's meant to go over 5, it prints 'Now trading under 6' then executes Under 5. Please assist. Attached the current one built below

[UNDER 9 BOT v1.txt](https://github.com/user-attachments/files/16541750/UNDER.9.BOT.v1.txt)

**Comment by binary-ex-machina** [comment]
@FrancisMairura I created the strategy in other way. I hope it is what you are looking for or at least help you in create the strategy you want

Download it here:  [under over switch.json.zip](https://github.com/user-attachments/files/17061550/under.over.switch.json.zip)

Run it at https://binaryblocks.pro/

![Screenshot 2023-10-25 at 13 35 02](https://github.com/binary-com/binary-bot/assets/34610787/1f77e711-fbd0-4572-a49a-45b958b475e8)
