### ISSUE TITLE
Even odd binary bot

### ISSUE THREAD

**Issue by ErnestoTrader** [binary-ex-machina/binaryblocks#47]
Hello, help me build a bot with the following strategy and should have a take profit, stop loss, martingale. The strategy is as follows:
The bot should analyse the over 4 and under 5 market in any volatility 1s market selected in 60ticks and place a trade in 1 tick. That is, if the the percentage of over 4 is 60% or more it should trade odd in 1tick and if under 5 is 60% or more it should trade even in one 1tick continuously until the percentage changes

**Comment by binary-ex-machina** [comment]
Hello, you can create one like this to achieve what you want

Download it here:  [Under Over Even Odd.json.zip](https://github.com/user-attachments/files/17591013/Under.Over.Even.Odd.json.zip)


Run it at https://binaryblocks.pro/

![Screenshot 2023-10-25 at 13 35 02](https://github.com/binary-com/binary-bot/assets/34610787/1f77e711-fbd0-4572-a49a-45b958b475e8)

![image](https://github.com/user-attachments/assets/e2c620d7-ab55-4a61-9832-cd2bdff69778)
