### ISSUE TITLE
Binary bot

### ISSUE THREAD

**Issue by ronojon** [binary-ex-machina/binaryblocks#48]
Hello, help me create a Rise Fall bot to analyze 100 ticks, and when the Rise percentage is above 55% its purchases Rise trades, and when the Fall percentage is above 55% it purchases Fall trades.

**Comment by binary-ex-machina** [comment]
Hello, you can achieve what you need by using the block to detect the amount of rise ticks

Download it here:  [Ticks 55.json.zip](https://github.com/user-attachments/files/17590794/Ticks.55.json.zip)


Run it at https://binaryblocks.pro/

![Screenshot 2023-10-25 at 13 35 02](https://github.com/binary-com/binary-bot/assets/34610787/1f77e711-fbd0-4572-a49a-45b958b475e8)

![image](https://github.com/user-attachments/assets/0a296575-5437-4b92-a642-6b3734c37213)
