### ISSUE TITLE
Deriv API explorer Buy contract 

### ISSUE THREAD

**Issue by t4vvd** [binary-ex-machina/binaryblocks#49]
Am missing a step in setting up the Buy contract after the Price Proposal but have lost how to arrive at the contract Id  to paste into the But Contract. eetc.To begin the first Buy . 
I,m still lacking most of the know how on setting the call request and response contract types . etc 
help would be appreciated . 
Thanks Paul.

**Comment by binary-ex-machina** [comment]
Hello @t4vvd, this repository is for things related to https://binaryblocks.pro only. If you have any questions about API, you must go to the Deriv repository
