### ISSUE TITLE
asking for help to create higher / Lower  bot That opens a trade based on the Previous candle eg if previous candle is a green candle then enter higher on the open of the next candle for the duration of the new candle etc

### ISSUE THREAD

**Issue by Fidzl** [binary-ex-machina/binaryblocks#5]

**Comment by binary-ex-machina** [comment]
@Fidzl you can do it like this image below

I used the barrier +/- 3, but you can adjust it. If you want to trade on every candle, lower the duration on both parameters to 54 and test.

download and unzip this file [higher_lower color.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/9854254/higher_lower.color.json.zip)

![image](https://user-images.githubusercontent.com/34610787/197597570-dabc6353-49e7-441f-a33c-e95093dfb909.png)

**Comment by Fidzl** [comment]
Thanks but i am unable to work with that file format. is it possible to get .xml

**Comment by binary-ex-machina** [comment]
The script only runs at https://binaryblocks.pro/
