### ISSUE TITLE
Binary bot

### ISSUE THREAD

**Issue by 808zic** [binary-ex-machina/binaryblocks#6]
Hello can you create a binary bot that trade type is digit even.
It should check if last digit is odd and appears 5 consecutive times then open a trade and purchase even digit for one tick then the bot can repeat the process

**Comment by binary-ex-machina** [comment]
Download [this](https://github.com/binary-ex-machina/binaryblocks/files/9992814/even.zip) file, unzip and try it.

You can change the digitsToCheck variable to the number of digits you want the system to check if they are odd to place trades.

![image](https://user-images.githubusercontent.com/34610787/201414360-262ba77c-4895-435b-8824-41a65436f8e7.png)

**Comment by 808zic** [comment]
Much appreciated
