### ISSUE TITLE
Hello, I would be interested in knowing how I can add the copy trading block in a functional way

### ISSUE THREAD

**Issue by smock1** [binary-ex-machina/binaryblocks#7]

**Comment by binary-ex-machina** [comment]
@smock1, you can setup copy trading like this image below, and insert any amount of tokens you want to use. They must be valid tokens, demo or real account

![image](https://user-images.githubusercontent.com/34610787/205938087-66cc95a2-eede-4c0b-a809-ad55d7433cc3.png)
