### ISSUE TITLE
Strategy 

### ISSUE THREAD

**Issue by DAVIE-M** [binary-ex-machina/binaryblocks#9]
Help me create a bot that uses EMA 50 and EMA 200. Such that if EMA 50 is over EMA 200 and the candle crosses EMA 50 upward the bot trades rise.. if EMA 50 is below ema 200 and the candle crosses EMA 50 downwards.. fall trade

**Comment by binary-ex-machina** [comment]
You can do this below

[ema 50x200 cross.json.zip](https://github.com/binary-ex-machina/binaryblocks/files/10521412/ema.50x200.cross.json.zip)

run it at [binaryblocks.pro](https://binaryblocks.pro)

![image](https://user-images.githubusercontent.com/34610787/215152403-1d03a53b-bd2f-46ce-861d-c07c321459a9.png)
